### ISSUE TITLE
Changes to account page

### ISSUE THREAD

**Issue by pddimitrova** [OpenMAVN/MAVN.Mobile#109]
ACs copied from epic:

Replace Community with My Account on navigation bar
Remove My Account icon from explore page
Change ordering of items on My Account page
Acceptance Criteria:

My Account as a main navigation item
Given I am signed in to the mobile app
When I check on the navigation icons
Then I see the following icons in order:
Explore; Offers; QR Code Scanner; Wallet; (My) Account
(2. Hide Account Icon from Home page)
Given I am on the Explore page of the mobile app
When I look at the top right of the screen
Then I do not see the My Account icon.

My Account ordering
Given I am signed in to the mobile app
When I Navigate to the My Account section
Then I see the following tabs in order:
Personal Details; Change Password; Referral Tracking; Link Business Account; Terms of Use; Privacy Policy; Contact Us; Sign in with your fingerprint; Logout

**Comment by HannaAndreevna** [comment]
Implemented
